name: mk
description: Biblio en ligne.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.1.4
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.6
  get_it: ^7.6.0
  file_picker: 5.2.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  infinite_carousel: ^1.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/slider/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

